version: '3'
services:

  db:
    image: postgres:9.6
    environment:
      LC_ALL: C.UTF-8
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - webmarks-network

  app:
    build: ./
    command: rails s -b 0.0.0.0
    depends_on:
      - db
    ports:
      - "80:3000"
    links:
      - db
    volumes:
      - .:/app
      - /bundle:/bundle
    networks:
      - webmarks-network

  bundle:
    image: busybox
    volumes:
      - /bundle

volumes:
  db-data:
    driver: local

networks:
    webmarks-network: